trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v1.0.0

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: linux
    name_postfix: _latest_git
    pre_test:
    - template: step--git-install.yml
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy3]
    os: linux
    name_postfix: _pypy
    pre_test:
    - script: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libxml2-dev libxslt1-dev
      displayName: install lxml dependencies
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py36, py37]
    os: linux
